# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: .+.diff$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: mixed-line-ending
        args: [--fix=lf]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.7'
    hooks:
    -   id: autopep8
        args: [--in-place, --max-line-length=120]
-   repo: https://github.com/emzeat/mz-lictools
    rev: v2.4.4
    hooks:
    -   id: license-tools
