name: Pull Request
run-name: Verifies conditions for a pull request
on:
  pull_request

jobs:
  pre-commit:
    runs-on: ubuntu
    container: ${{ env.MZ_DOCKER_REGISTRY }}/pre-commit:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Check hooks
        run: |
          set -ex
          # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
          pre-commit run \
            --from-ref ${{ gitea.event.pull_request.base.sha }} \
            --to-ref ${{ gitea.event.pull_request.head.sha }} \
            --all-files \
            --verbose \
            --show-diff-on-failure

  build-and-test:
    strategy:
      matrix:
        include:
          - runner: ubuntu-2004-large
            compiler: clang
            generator: ninja
          - runner: ubuntu-2004-large
            compiler: gcc
            generator: ninja
          - runner: windows-large
            compiler: msvc
            generator: ninja_64
          - runner: macos-large
            compiler: clang
            generator: ninja
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            lfs: 'true'
            submodules: 'true'
            fetch-depth: 0
      - name: Configure
        run: |
          set -ex
          bash ./build/generator.sh \
            compiler=${{ matrix.compiler }} \
            generator=${{ matrix.generator }} \
            mode=release \
            location=inside \
            -DCONAN_BUILD_MISSING=ON
      - name: Build
        run: |
          set -ex
          cmake \
            --build -j 12 \
            --preset ${{ matrix.compiler }}-${{ matrix.generator }}-release
      - name: Package
        run: |
          set -ex
          source ./build/conan.sh
          python3 build/conan_package.py --create --verbose
      - name: Test
        run: |
          set -ex
          ctest \
            -j 1 \
            --preset ${{ matrix.compiler }}-${{ matrix.generator }}-release
