name: Pull Request
run-name: Verifies conditions for a pull request
on:
  pull_request

jobs:
  pre-commit:
    runs-on: ubuntu
    container: ${{ env.MZ_DOCKER_REGISTRY }}/pre-commit:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check hooks
        run: pre-commit run --all-files --verbose --show-diff-on-failure

  build-and-test:
    strategy:
      matrix:
        include:
          - runner: ubuntu-1804-large
            compiler: clang
            generator: ninja
          - runner: windows-large
            compiler: msvc
            generator: ninja_64
          - runner: macos-large
            compiler: clang
            generator: ninja
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: ${{ env.RUNNER_SHELL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            lfs: 'true'
            submodules: 'true'
            fetch-depth: 0
      - name: Configure
        run: bash ./build/generator.sh compiler=${{ matrix.compiler }} generator=${{ matrix.generator }} mode=release location=inside -DMZ_DO_CPPLINT_DIFF=OFF
      - name: Build
        run: cmake --build -j 12 --preset ${{ matrix.compiler }}-${{ matrix.generator }}-release
      - name: Package
        run: python3 build/conan_package.py --create
      - name: Test
        run: ctest -j 1 --preset ${{ matrix.compiler }}-${{ matrix.generator }}-release
